// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
//
// --------------------------------------------------------------------------
// $Maintainer: Kyowon Jeong, Jihyung Kim, Jaekwan Kim $
// $Authors: Kyowon Jeong, Jihyung Kim, Jaekwan Kim $
// --------------------------------------------------------------------------

#include <OpenMS/ANALYSIS/TOPDOWN/DeconvolvedSpectrum.h>
#include <OpenMS/ANALYSIS/TOPDOWN/FLASHDeconvAlgorithm.h>
#include <OpenMS/ANALYSIS/TOPDOWN/MassFeatureTrace.h>
#include <OpenMS/ANALYSIS/TOPDOWN/PeakGroup.h>
#include <OpenMS/ANALYSIS/TOPDOWN/Qvalue.h>
#include <OpenMS/ANALYSIS/TOPDOWN/TopDownIsobaricQuantification.h>
#include <OpenMS/MATH/STATISTICS/GaussFitter.h>
#include <OpenMS/METADATA/SpectrumLookup.h>
#include <OpenMS/PROCESSING/FILTERING/ThresholdMower.h>
#include <OpenMS/PROCESSING/SPECTRAMERGING/SpectraMerger.h>
#include <exception>
#include <iterator>
#include <memory>
#include <numeric>
#include <optional>
#include <set>
#include <utility>

#ifdef _OPENMP
  #include <omp.h>
#endif

namespace OpenMS
{
inline const Size max_peak_count_for_centroid_ = 3e4;
inline const Size max_peak_count_for_profile_ = 1e5;

FLASHDeconvAlgorithm::FLASHDeconvAlgorithm(): DefaultParamHandler("FLASHDeconvAlgorithm"), ProgressLogger()
{
  // FLASHIda log file read somewhere. ida_log_file_ should be updated.
  defaults_.setValue("ida_log", "", "Provide the log file generated by FLASHIda (e.g., IDA*.log) for coupling with FLASHIda acquisition.");
  defaults_.setValue(
    "report_FDR", "false",
    "Generate q-values (approximate FDR) for deconvolved masses. Decoy masses are also reported which were used for FDR calculation. (Beta version)");
  defaults_.setValidStrings("report_FDR", {"true", "false"});

  defaults_.setValue("allowed_isotope_error", 0,
                     "Tolerance for isotope index errors when calculating FDR. For instance, setting a value of 2 permits the inclusion of up to 2 "
                     "isotope errors as valid matches. Beta version.");
  defaults_.addTag("allowed_isotope_error", "advanced");

  defaults_.setValue("use_RNA_averagine", "false", "Use the RNA (nucleotide) averagine model for deconvolution.");
  defaults_.setValidStrings("use_RNA_averagine", {"true", "false"});
  defaults_.addTag("use_RNA_averagine", "advanced");

  defaults_.setValue(
    "precursor_MS1_window", 1,
    "Number of MS1 spectra around each MS2 spectrum to search for precursor peaks when determining the MS2 precursors. For MS2 spectrum, the mass of "
    "precursor ion should be determined for better deconvolution and reliable identification. "
    "If the mass of precursor ion is not found in the immediately preceding MS1 spectrum, previous or next MS1 spectra may be used instead. "
    "This parameter determines up to how many MS1 spectra around each MS2 spectrum will be searched.");
  defaults_.setMinInt("precursor_MS1_window", 1);
  defaults_.addTag("precursor_MS1_window", "advanced");

  defaults_.setValue("isolation_window", 5.0,
                     "Specify the isolation window width for precursor determination. Used when this information is absent in the mzML file.");
  defaults_.addTag("isolation_window", "advanced");

  defaults_.setValue("merging_method", 0,
                     "Method for merging spectra before deconvolution. 0: No merging  1: Gaussian averaging per MS level, effective for Q-TOF "
                     "datasets. For MSn (n > 1), only the spectra from the same precursor mass "
                     "(subject to tolerance set by SD:tol) are averaged. 2: Block merging, combining all spectra into one per MS level (e.g., for "
                     "NativeMS datasets).");
  defaults_.setMinInt("merging_method", 0);
  defaults_.setMaxInt("merging_method", 2);

  defaults_.setValue("merging_min_ms_level", 1, "Min MS level for merging");
  defaults_.setValue("merging_max_ms_level", 2, "Max MS level for merging");
  defaults_.setMinInt("merging_min_ms_level", 1);
  defaults_.setMinInt("merging_max_ms_level", 1);

  auto sd_defaults = SpectralDeconvolution().getDefaults();
  sd_defaults.remove("allowed_isotope_error");
  defaults_.insert("SD:", sd_defaults);

  Param mf_defaults = MassFeatureTrace().getDefaults();
  mf_defaults.setValue("min_cos", -1.0,
                       "Cosine similarity threshold between avg. and observed isotope pattern. When negative, MS1 cosine threshold for spectral "
                       "deconvolution (set by -SD:min_cos will be used ");
  mf_defaults.setValue("mass_error_ppm", -1.0,
                       "Specifies the mass error tolerance for feature tracing in ppm. When negative, the MS1 tolerance for deconvolution is used "
                       "(e.g., 16 ppm is used when -SD:tol 16).");
  mf_defaults.addTag("min_cos", "advanced");
  mf_defaults.addTag("mass_error_ppm", "advanced");

  mf_defaults.remove("noise_threshold_int");
  mf_defaults.remove("reestimate_mt_sd");
  mf_defaults.remove("trace_termination_criterion");
  mf_defaults.remove("trace_termination_outliers");
  mf_defaults.remove("chrom_peak_snr");

  defaults_.insert("ft:", mf_defaults);
  defaults_.insert("iq:", TopDownIsobaricQuantification().getDefaults());

  defaultsToParam_();
}

void FLASHDeconvAlgorithm::updateMembers_()
{
  tols_ = param_.getValue("SD:tol");
  min_cos_ = param_.getValue("SD:min_cos");
  precursor_MS1_window_ = param_.getValue("precursor_MS1_window");
  use_RNA_averagine_ = param_.getValue("use_RNA_averagine") != "false";
  report_decoy_ = param_.getValue("report_FDR") != "false";

  merge_spec_ = param_.getValue("merging_method");
  isolation_window_size_ = param_.getValue("isolation_window");
  ida_log_file_ = param_.getValue("ida_log").toString();
  current_min_ms_level_ = max_ms_level_;
  current_max_ms_level_ = 0;
}

void FLASHDeconvAlgorithm::updateMSLevels_(MSExperiment& map)
{
  // read input dataset once to count spectra
  for (auto& it : map)
  {
    // if forced_ms_level > 0, force MS level of all spectra to 1.
    if (forced_ms_level_ > 0) { it.setMSLevel(forced_ms_level_); }

    if (it.empty()) { continue; }
    if (it.getMSLevel() > max_ms_level_) { continue; }

    uint ms_level = it.getMSLevel();
    current_max_ms_level_ = current_max_ms_level_ < ms_level ? ms_level : current_max_ms_level_;
    current_min_ms_level_ = current_min_ms_level_ > ms_level ? ms_level : current_min_ms_level_;
  }
  // Max MS Level is adjusted according to the input dataset
  current_max_ms_level_ = current_max_ms_level_ > max_ms_level_ ? max_ms_level_ : current_max_ms_level_;
}

void FLASHDeconvAlgorithm::filterLowPeaks_(MSExperiment& map)
{
  OPENMS_LOG_INFO << "Filtering low peaks in spectra ... ";
  ThresholdMower threshold_mower_filter;                         // threshold
  Param t_filter_param = threshold_mower_filter.getParameters(); //"threshold", .00001
  t_filter_param.setValue("threshold", 1e-6);
  threshold_mower_filter.setParameters(t_filter_param);

  const auto trim_spectrum = [](MSSpectrum& it) {
    if (it.empty()) return;
    Size count = it.getType(false) == SpectrumSettings::SpectrumType::CENTROID ? max_peak_count_for_centroid_ : max_peak_count_for_profile_;
    it.sortByIntensity(true);
    // There is no element at count when exactly count peaks remain.
    double threshold = it.size() <= count ? 0 : it[count].getIntensity();
    threshold = std::max(threshold, (double)it.begin()->getIntensity() / 1000);
    // pop back the low intensity peaks using threshold

    while (! it.empty() && it.back().getIntensity() <= threshold)
    {
      it.pop_back();
    }
    it.sortByPosition();
  };

  // Release spare peak storage after trimming without replacing the spectrum
  // object or its metadata. Array shrink requests leave their values intact.
  const auto compact_spectrum = [](MSSpectrum& it) {
    MSSpectrum::ContainerType compact_peaks(it.cbegin(), it.cend());
    it.swap(compact_peaks);
    for (auto& array : it.getFloatDataArrays())
    {
      array.shrink_to_fit();
    }
    for (auto& array : it.getIntegerDataArrays())
    {
      array.shrink_to_fit();
    }
    for (auto& array : it.getStringDataArrays())
    {
      array.shrink_to_fit();
    }
  };

  // Array selection can throw before filtering or after peak-only trimming.
  // Preserve the original threshold pass and use serial exception construction
  // whenever a spectrum carries an array collection, including empty arrays.
  const bool has_data_arrays = std::any_of(map.begin(), map.end(), [](const MSSpectrum& it) {
    return ! it.getFloatDataArrays().empty() || ! it.getIntegerDataArrays().empty() || ! it.getStringDataArrays().empty();
  });
  if (has_data_arrays)
  {
    threshold_mower_filter.filterPeakMap(map);
    for (auto& it : map)
    {
      trim_spectrum(it);
      compact_spectrum(it);
    }
    OPENMS_LOG_INFO << "Done" << std::endl;
    return;
  }

  // ThresholdMower updates its own threshold during each call. Clone the
  // configured filter on the caller before assigning distinct spectra.
  int worker_count = 1;
#ifdef _OPENMP
  worker_count = static_cast<int>(std::max<Size>(1, std::min<Size>(omp_get_max_threads(), map.size())));
#endif
  std::vector<ThresholdMower> filters(worker_count, threshold_mower_filter);
  std::vector<std::exception_ptr> errors(map.size());
#pragma omp parallel for default(none) num_threads(worker_count) shared(map, filters, errors, trim_spectrum, compact_spectrum)
  for (int i = 0; i < (int)map.size(); i++)
  {
    int worker_index = 0;
#ifdef _OPENMP
    worker_index = omp_get_thread_num();
#endif
    try
    {
      auto& it = map[i];
      filters[worker_index].filterSpectrum(it);
      trim_spectrum(it);
      compact_spectrum(it);
    }
    catch (...)
    {
      errors[i] = std::current_exception();
    }
  }
  // Report the earliest input-index error after the whole workshare has joined.
  for (const auto& error : errors)
  {
    if (error) { std::rethrow_exception(error); }
  }
  OPENMS_LOG_INFO << "Done" << std::endl;
}

void FLASHDeconvAlgorithm::mergeSpectra_(MSExperiment& map, uint ms_level)
{
  SpectraMerger merger;
  merger.setLogType(CMD);
  Param sm_param = merger.getDefaults();
  sm_param.setValue("mz_binning_width", tols_[ms_level - 1] / 2.5);
  sm_param.setValue("mz_binning_width_unit", "ppm");
  uint min_ms_level = param_.getValue("merging_min_ms_level");
  uint max_ms_level = param_.getValue("merging_max_ms_level");
  if (merge_spec_ == 1 && ms_level >= min_ms_level && ms_level <= max_ms_level)
  {
    if (ms_level == 1)
    {
      OPENMS_LOG_INFO << "Gaussian averaging MS1 spectra ... " << std::endl;
      merger.setParameters(sm_param);
      map.sortSpectra();
      merger.average(map, "gaussian", (int)ms_level);
    }
    else
    {
      // For ms n, first find precursors for all ms n. then make a tmp map having the precursor masses as precursor
      std::map<std::string, std::vector<Precursor>> original_precursor_map;
#pragma omp parallel for default(none), shared(map, ms_level, original_precursor_map)
      for (int i = 0; i < (int)map.size(); i++)
      {
        auto spec = map[i];
        if (spec.getMSLevel() != ms_level) continue;

        const auto& native_id = spec.getNativeID();
        original_precursor_map[native_id] = spec.getPrecursors();

        if (! spec.getPrecursors().empty() && native_id_precursor_peak_group_map_.contains(native_id))
        {
          auto precursor_pg = native_id_precursor_peak_group_map_[native_id];
          auto precursor = spec.getPrecursors()[0];
          precursor.setCharge(1);
          precursor.setMZ(precursor_pg.getMonoMass());
          precursor.setIntensity(precursor_pg.getIntensity());
          map[i].setPrecursors(std::vector<Precursor> {precursor});
        }
      }
      // merge MS n using precursor method
      OPENMS_LOG_INFO << "Merging MS" << ms_level << " spectra from the same deconvolved precursor masses... " << std::endl;
      sm_param.setValue("precursor_method:mz_tolerance", 0.2);
      sm_param.setValue("precursor_method:rt_tolerance", 30.0); // TODO make this as a user input?
      merger.setParameters(sm_param);
      map.sortSpectra();
      merger.mergeSpectraPrecursors(map);

      for (auto& mspec : map)
      {
        auto native_id_str = mspec.getNativeID();
        std::vector<std::string> native_ids;
        StringUtils::split(native_id_str, ",", native_ids);

        for (auto& native_id : native_ids)
        {
          if (! original_precursor_map.contains(native_id)) continue;
          mspec.setPrecursors(original_precursor_map[native_id]);
        }
      }
    }
  }
  else if (merge_spec_ == 2)
  {
    OPENMS_LOG_INFO << "Merging spectra into a single spectrum for MS" << ms_level << std::endl;
    sm_param.setValue("block_method:rt_block_size", map.size() + 1);
    map.sortSpectra();
    sm_param.setValue("block_method:ms_levels", IntList {(int)ms_level});
    merger.setParameters(sm_param);
    merger.mergeSpectraBlockWise(map);
  }
  filterLowPeaks_(map);
}

int FLASHDeconvAlgorithm::getScanNumber(const MSExperiment& map, Size index)
{
  auto native_id_str = map[index].getNativeID();
  std::vector<std::string> native_ids;
  StringUtils::split(native_id_str, ",", native_ids);
  std::string type_accession = "MS:1000768";

  if (! map.getSourceFiles().empty())
  {
    type_accession = map.getSourceFiles()[0].getNativeIDTypeAccession();
    if (type_accession.empty()) type_accession = "MS:1000768";
  }
  int scan_number = SpectrumLookup::extractScanNumber(native_ids.back(), type_accession);
  if (scan_number < 0) { scan_number = (int)index + 1; }

  return scan_number;
}

std::vector<double> FLASHDeconvAlgorithm::getTolerances() const
{ return tols_; }

int FLASHDeconvAlgorithm::findPrecursorScanNumber_(const MSExperiment& map, Size index, uint ms_level) const
{
  for (int p_index = (int)index - 1; p_index >= 0; p_index--)
  {
    if (map[p_index].getMSLevel() == ms_level - 1) { return getScanNumber(map, p_index); }
  }
  return -1;
}

void FLASHDeconvAlgorithm::appendDecoyPeakGroups_(DeconvolvedSpectrum& deconvolved_spectrum,
                                                  const MSSpectrum& spec,
                                                  int scan_number,
                                                  const PeakGroup& precursor_pg)
{
#pragma omp parallel sections default(none) shared(spec, scan_number, precursor_pg, deconvolved_spectrum)
  {
#pragma omp section
    sd_noise_decoy_.performSpectrumDeconvolution(spec, scan_number, precursor_pg);
#pragma omp section
    sd_signal_decoy_.performSpectrumDeconvolution(spec, scan_number, precursor_pg);
  }
  deconvolved_spectrum.sortByQscore();

  deconvolved_spectrum.reserve(deconvolved_spectrum.size() + sd_signal_decoy_.getDeconvolvedSpectrum().size()
                               + sd_noise_decoy_.getDeconvolvedSpectrum().size());

  for (const auto& pg : sd_signal_decoy_.getDeconvolvedSpectrum())
  {
    deconvolved_spectrum.push_back(pg);
  }

  for (const auto& pg : sd_noise_decoy_.getDeconvolvedSpectrum())
  {
    deconvolved_spectrum.push_back(pg);
  }

  deconvolved_spectrum.sort();
}

void FLASHDeconvAlgorithm::runSpectralDeconvolution_(MSExperiment& map, std::vector<DeconvolvedSpectrum>& deconvolved_spectra)
{
  startProgress(0, (SignedSize)map.size(), "running FLASHDeconv");
  std::map<double, int> rt_scan_map;
  std::vector<int> scan_numbers(map.size());
  for (Size index = 0; index < map.size(); index++)
  {
    int scan_number = getScanNumber(map, index);
    scan_numbers[index] = scan_number;
    rt_scan_map[map[index].getRT()] = scan_number;
  }

  // Outer parallelism is restricted to the ordinary target path.
  // Keep merging, FDR, FLASHIda and manual precursor overrides on the serial path.
  int worker_count = 0;
#ifdef _OPENMP
  const auto& worker_parameters = sd_.getParameters();
  if (! report_decoy_ && merge_spec_ == 0 && ida_log_file_.empty() && omp_get_level() == 0 && (int)worker_parameters.getValue("precursor_charge") == 0
      && (double)worker_parameters.getValue("precursor_mz") == 0)
  {
    std::vector<Size> level_counts(current_max_ms_level_ + 1, 0);
    for (const auto& spec : map)
    {
      if (! spec.empty() && spec.getMSLevel() <= current_max_ms_level_) { ++level_counts[spec.getMSLevel()]; }
    }
    worker_count = (int)std::min((Size)omp_get_max_threads(), *std::max_element(level_counts.begin(), level_counts.end()));
  }
#endif
  // Construct in stable storage rather than copying mutable SD state/pointers.
  std::vector<SpectralDeconvolution> spectrum_workers(worker_count > 1 ? worker_count : 0);
  // One immutable per-run copy replaces all worker model copies. No pool lock
  // or shared_ptr reference-count operation is used during spectrum scoring.
  const auto shared_averagine = spectrum_workers.empty() ? std::shared_ptr<const SpectralDeconvolution::PrecalculatedAveragine>()
                                                         : std::make_shared<const SpectralDeconvolution::PrecalculatedAveragine>(sd_.getAveragine());
  for (auto& worker : spectrum_workers)
  {
    worker.setParameters(sd_.getParameters());
    worker.setSharedAveragine_(shared_averagine);
  }

  for (uint ms_level = 1; ms_level <= current_max_ms_level_; ms_level++)
  {
    if (ms_level > 1) { findPrecursorPeakGroupsForMSnSpectra_(map, deconvolved_spectra, ms_level); }

    if (merge_spec_ > 0)
    {
      mergeSpectra_(map, ms_level);
      if (ms_level > 1) { findPrecursorPeakGroupsForMSnSpectra_(map, deconvolved_spectra, ms_level); }
    }

    if (! spectrum_workers.empty())
    {
      std::vector<Size> spectrum_indices;
      std::vector<int> fallback_scans;
      std::vector<const PeakGroup*> precursors;
      const auto& precursor_groups = native_id_precursor_peak_group_map_;
      int previous_lower_scan = 0;
      Size progress_count = 0;
      for (Size index = 0; index < map.size(); ++index)
      {
        const auto& spec = map[index];
        if (spec.getMSLevel() == ms_level - 1) { previous_lower_scan = scan_numbers[index]; }
        if (spec.getMSLevel() != ms_level) { continue; }
        ++progress_count;
        if (spec.empty()) { continue; }
        spectrum_indices.push_back(index);
        fallback_scans.push_back(previous_lower_scan);
        const auto precursor = precursor_groups.find(spec.getNativeID());
        precursors.push_back(precursor == precursor_groups.end() ? nullptr : &precursor->second);
      }

      if (spectrum_indices.size() > 1)
      {
        std::vector<std::optional<DeconvolvedSpectrum>> level_results(spectrum_indices.size());
        std::vector<std::exception_ptr> errors(spectrum_indices.size());
        const PeakGroup empty_precursor;
        int level_workers = (int)std::min(spectrum_workers.size(), spectrum_indices.size());
#pragma omp parallel num_threads(level_workers) default(none) \
  shared(map, spectrum_indices, scan_numbers, fallback_scans, precursors, empty_precursor, spectrum_workers, level_results, errors, ms_level)
        {
          int worker_index = 0;
#ifdef _OPENMP
          worker_index = omp_get_thread_num();
#endif
          auto& worker = spectrum_workers[worker_index];
#pragma omp for schedule(dynamic, 1)
          for (SignedSize job = 0; job < (SignedSize)spectrum_indices.size(); ++job)
          {
            try
            {
              const Size index = spectrum_indices[job];
              const auto& precursor = precursors[job] == nullptr ? empty_precursor : *precursors[job];
              worker.performSpectrumDeconvolution(map[index], scan_numbers[index], precursor);
              auto& result = worker.getDeconvolvedSpectrum();
              if (ms_level > 1 && precursor.empty()) { result.setPrecursorScanNumber(fallback_scans[job]); }
              // Assignment would copy: DeconvolvedSpectrum has no move assignment.
              level_results[job].emplace(std::move(result));
            }
            catch (...)
            {
              errors[job] = std::current_exception();
            }
          }
        }
        // Commit in input order, including equal scan-number keys, after join.
        for (const auto& error : errors)
        {
          if (error)
          {
            endProgress();
            std::rethrow_exception(error);
          }
        }
        deconvolved_spectra.reserve(deconvolved_spectra.size() + level_results.size());
        for (auto& result : level_results)
        {
          deconvolved_spectra.emplace_back(std::move(*result));
        }
        for (Size i = 0; i < progress_count; ++i)
        {
          nextProgress();
        }
        // Sort the same scan-only keys without copying full spectra in assignments.
        std::vector<Size> order(deconvolved_spectra.size());
        std::iota(order.begin(), order.end(), 0);
        std::sort(order.begin(), order.end(), [&deconvolved_spectra](Size a, Size b) { return deconvolved_spectra[a] < deconvolved_spectra[b]; });
        std::vector<DeconvolvedSpectrum> ordered_spectra;
        ordered_spectra.reserve(deconvolved_spectra.size());
        for (Size index : order)
        {
          ordered_spectra.emplace_back(std::move(deconvolved_spectra[index]));
        }
        deconvolved_spectra.swap(ordered_spectra);
        continue;
      }
    }

    for (Size index = 0; index < map.size(); index++)
    {
      int scan_number = merge_spec_ == 0 ? getScanNumber(map, index)
                                         : (! rt_scan_map.contains(map[index].getRT()) ? getScanNumber(map, index) : rt_scan_map[map[index].getRT()]);
      const auto& spec = map[index];

      if (ms_level != spec.getMSLevel()) { continue; }
      nextProgress();
      if (spec.empty()) { continue; }

      std::string native_id = spec.getNativeID();
      PeakGroup precursor_pg;
      if (native_id_precursor_peak_group_map_.contains(native_id)) { precursor_pg = native_id_precursor_peak_group_map_[native_id]; }

      sd_.performSpectrumDeconvolution(spec, scan_number, precursor_pg);
      auto& deconvolved_spectrum = sd_.getDeconvolvedSpectrum();

      if (ms_level > 1 && precursor_pg.empty())
      {
        int precursor_scan = findPrecursorScanNumber_(map, index, ms_level);
        if (precursor_scan >= 0) { deconvolved_spectrum.setPrecursorScanNumber(precursor_scan); }
      }

      if (report_decoy_ && ! deconvolved_spectrum.empty()) { appendDecoyPeakGroups_(deconvolved_spectrum, spec, scan_number, precursor_pg); }

      deconvolved_spectra.push_back(deconvolved_spectrum);
    }
    std::sort(deconvolved_spectra.begin(), deconvolved_spectra.end());
  }
  endProgress();
}


const FLASHHelperClasses::PrecalculatedAveragine& FLASHDeconvAlgorithm::getAveragine()
{ return sd_.getAveragine(); }

const FLASHHelperClasses::PrecalculatedAveragine& FLASHDeconvAlgorithm::getDecoyAveragine()
{
  if (! report_decoy_) return getAveragine();
  return sd_noise_decoy_.getAveragine();
}

std::vector<int> FLASHDeconvAlgorithm::getHistogram_(const std::vector<double>& data, double min_range, double max_range, double bin_size)
{
  int num_bins = static_cast<int>((max_range - min_range) / bin_size) + 1;
  std::vector<int> bins(num_bins, 0);

  // Populate the bins
  for (double value : data)
  {
    if (value >= min_range && value <= max_range)
    {
      int bin_index = static_cast<int>((value - min_range) / bin_size);
      bins[bin_index]++;
    }
  }
  return bins;
}

void FLASHDeconvAlgorithm::determineTolerance_(const MSExperiment& map,
                                               const Param& sd_param,
                                               const FLASHHelperClasses::PrecalculatedAveragine& avg,
                                               const uint ms_level)
{
  OPENMS_LOG_INFO << "Determining tolerance for MS" << ms_level << " ... ";
  auto sd = SpectralDeconvolution();
  auto sd_param_t = sd_param;
  sd.setAveragine(avg);
  tols_[ms_level - 1] = 200;             // maximum tolerance
  sd_param_t.setValue("min_charge", 1);  // better to include charge 1 to determine ppm error.
  sd_param_t.setValue("min_mass", 50.0); // better to include small masses to determine ppm error.
  sd_param_t.setValue("tol", tols_);
  sd.setParameters(sd_param_t);
  sd.setToleranceEstimation();

  int sample_rate = 100; //
  int count = 0;
  std::vector<double> sampled_tols;
  for (const auto& spec : map)
  {
    if (ms_level != (uint)spec.getMSLevel()) { continue; }
    if (spec.empty()) { continue; }
    if (count++ % sample_rate != 0) continue;
    PeakGroup precursor_pg;
    sd.performSpectrumDeconvolution(spec, 0, precursor_pg);

    const auto& deconvolved_spectrum = sd.getDeconvolvedSpectrum(); // estimate both.

    for (const auto& pg : deconvolved_spectrum)
    {
      if (pg.getQscore() < .9) // TODO automatically find the good mass threshold
        continue;
      for (auto error : pg.getMassErrors())
      {
        sampled_tols.push_back(error);
      }
    }
  }

  if (sampled_tols.size() < 6)
  {
    OPENMS_LOG_INFO << "failed. Cannot be determined - no MS" << ms_level << " spectrum. Set to 10ppm (default tolerance)." << std::endl;
    tols_[ms_level - 1] = 10;
    return;
  }

  try
  {
    const int l = -100, r = 100, bin_size = 1;
    const auto& bins = getHistogram_(sampled_tols, l, r, bin_size);
    // Calculate mean using std::accumulate

    std::vector<DPosition<2>> points;
    for (int b = l; b <= r; b += bin_size)
    {
      points.emplace_back(b, bins[b - l]);
    }
    Math::GaussFitter fitter;
    const auto fit = fitter.fit(points);

    tols_[ms_level - 1] = round(fit.sigma * 2.17 * 2); // 97% area under curve in gaussian
    OPENMS_LOG_INFO << "done. Determined tolerance: " << tols_[ms_level - 1] << " ppm. You may test around this tolerance for better results."
                    << std::endl;
  }
  catch (const Exception::UnableToFit& e)
  {
    // Handle the exception and issue a warning
    OPENMS_LOG_INFO << "failed. Cannot be determined - Gaussian fitting failure. Set to 10ppm (default tolerance)." << std::endl;
    tols_[ms_level - 1] = 10;
  }
  catch (const std::exception& e)
  {
    // Handle other exceptions if necessary
    OPENMS_LOG_INFO << "failed. Cannot be determined - Gaussian fitting failure. Set to 10ppm (default tolerance)." << std::endl;
    tols_[ms_level - 1] = 10;
  }
}

void FLASHDeconvAlgorithm::run(MSExperiment& map,
                               std::vector<DeconvolvedSpectrum>& deconvolved_spectra,
                               std::vector<FLASHHelperClasses::MassFeature>& deconvolved_features)
{
  updateMSLevels_(map);
  filterLowPeaks_(map);

  sd_ = SpectralDeconvolution();
  Param sd_param = param_.copy("SD:", true);
  sd_param.setValue("allowed_isotope_error", param_.getValue("allowed_isotope_error"));
  OPENMS_LOG_INFO << "Calculating Averagines ... " << std::flush;
  sd_.setParameters(sd_param);
  sd_.calculateAveragine(use_RNA_averagine_);
  OPENMS_LOG_INFO << "Done" << std::endl;
  const auto& avg = sd_.getAveragine();

  // determine tolerance in case tolerance input is negative
  for (uint ms_level = 1; ms_level <= current_max_ms_level_; ms_level++)
  {
    if (tols_[ms_level - 1] > 0) continue;
    determineTolerance_(map, sd_param, avg, ms_level);
  }

  sd_param.setValue("tol", tols_);
  sd_.setParameters(sd_param);

  if (report_decoy_)
  {
    sd_noise_decoy_.setParameters(sd_param);
    sd_noise_decoy_.setTargetDecoyType(PeakGroup::TargetDecoyType::noise_decoy, sd_.getDeconvolvedSpectrum()); // noise
    sd_noise_decoy_.calculateAveragine(use_RNA_averagine_); // for noise, averagine needs to be calculated differently.

    sd_signal_decoy_.setParameters(sd_param);
    sd_signal_decoy_.setTargetDecoyType(PeakGroup::TargetDecoyType::signal_decoy, sd_.getDeconvolvedSpectrum()); // isotope
    sd_signal_decoy_.setAveragine(avg);
  }

  setLogType(CMD);
  deconvolved_spectra.reserve(map.size() * 4);

  // run spectral deconvolution here and get deconvolved spectra
  runSpectralDeconvolution_(map, deconvolved_spectra);

  // feature tracing here and update FeatureQScores
  runFeatureFinding_(deconvolved_spectra, deconvolved_features);

  noise_decoy_weight_ = Qvalue::updatePeakGroupQvalues(deconvolved_spectra);

  TopDownIsobaricQuantification quantifier;
  Param quant_param = param_.copy("iq:", true);
  quantifier.setParameters(quant_param);
  // Isobaric quant run
  quantifier.quantify(map, deconvolved_spectra, deconvolved_features);
}

std::pair<int, int> FLASHDeconvAlgorithm::findScanNumberBounds_(const MSExperiment& map, Size index, uint ms_level) const
{
  // find beginning scan number
  int num_precursor_window = ms_level == 2 ? precursor_MS1_window_ : 1;
  auto index_copy = index;
  while (index_copy > 0 && num_precursor_window > 0)
  {
    index_copy--;
    if (map[index_copy].getMSLevel() == ms_level - 1) { num_precursor_window--; }
  }
  int b_scan_number = getScanNumber(map, index_copy);

  // find ending scan number
  index_copy = index;
  num_precursor_window = ms_level == 2 ? precursor_MS1_window_ : 0;
  while (index_copy < map.size() - 1 && num_precursor_window > 0)
  {
    index_copy++;
    if (map[index_copy].getMSLevel() == ms_level - 1) { num_precursor_window--; }
  }
  int a_scan_number = getScanNumber(map, index_copy);

  return {b_scan_number, a_scan_number};
}

std::vector<DeconvolvedSpectrum> FLASHDeconvAlgorithm::collectSurveyScans_(const std::vector<DeconvolvedSpectrum>& deconvolved_spectra,
                                                                           int b_scan_number,
                                                                           int a_scan_number,
                                                                           uint ms_level) const
{
  std::vector<DeconvolvedSpectrum> survey_scans;

  auto diter = std::lower_bound(deconvolved_spectra.begin(), deconvolved_spectra.end(), DeconvolvedSpectrum(b_scan_number));
  auto aiter = std::lower_bound(deconvolved_spectra.begin(), deconvolved_spectra.end(), DeconvolvedSpectrum(a_scan_number));

  if (diter == deconvolved_spectra.end()) { return survey_scans; }

  while (diter < deconvolved_spectra.end() && diter <= aiter)
  {
    if (diter->getOriginalSpectrum().getMSLevel() == ms_level - 1) { survey_scans.push_back(*diter); }
    diter++;
  }

  return survey_scans;
}

std::pair<double, double> FLASHDeconvAlgorithm::getIsolationWindowMzRange_(const MSSpectrum& spec) const
{
  double start_mz = 0;
  double end_mz = 0;

  for (const auto& precursor : spec.getPrecursors())
  {
    double loffset = precursor.getIsolationWindowLowerOffset();
    double uoffset = precursor.getIsolationWindowUpperOffset();
    loffset = loffset <= 0 ? isolation_window_size_ / 2.0 : loffset;
    uoffset = uoffset <= 0 ? isolation_window_size_ / 2.0 : uoffset;

    start_mz = loffset > 100.0 ? loffset : -loffset + precursor.getMZ();
    end_mz = uoffset > 100.0 ? uoffset : uoffset + precursor.getMZ();
  }

  return {start_mz, end_mz};
}

PeakGroup
FLASHDeconvAlgorithm::findBestPrecursorPeakGroup_(const std::vector<DeconvolvedSpectrum>& survey_scans, double start_mz, double end_mz) const
{
  PeakGroup best_pg;
  double max_score = -1.0;

  for (int i = (int)survey_scans.size() - 1; i >= 0; i--)
  {
    const auto& precursor_spectrum = survey_scans[i];
    if (precursor_spectrum.empty()) { continue; }

    for (const auto& pg : precursor_spectrum)
    {
      if (pg[0].mz > end_mz || pg[pg.size() - 1].mz < start_mz) { continue; }

      double max_intensity = 0.0;
      const FLASHHelperClasses::LogMzPeak* tmp_precursor = nullptr;

      int c = int(round(pg.getMonoMass() / start_mz));
      for (const auto& tmp_peak : pg)
      {
        if (tmp_peak.abs_charge != c) { continue; }
        if (tmp_peak.mz < start_mz || tmp_peak.mz > end_mz) { continue; }
        if (tmp_peak.intensity < max_intensity) { continue; }
        max_intensity = tmp_peak.intensity;
        tmp_precursor = &tmp_peak;
      }

      if (tmp_precursor == nullptr) { continue; }

      auto score = pg.getChargeSNR(tmp_precursor->abs_charge);
      if (score < max_score) { continue; }
      max_score = score;
      best_pg = pg;
    }

    if (! best_pg.empty()) { break; }
  }

  return best_pg;
}

void FLASHDeconvAlgorithm::findPrecursorPeakGroupsForMSnSpectra_(const MSExperiment& map,
                                                                 const std::vector<DeconvolvedSpectrum>& deconvolved_spectra,
                                                                 uint ms_level)
{
  bool parallel_registration = false;
#ifdef _OPENMP
  const auto& parameters = sd_.getParameters();
  parallel_registration = ! report_decoy_ && merge_spec_ == 0 && ida_log_file_.empty() && omp_get_level() == 0 && omp_get_max_threads() > 1
                          && (int)parameters.getValue("precursor_charge") == 0 && (double)parameters.getValue("precursor_mz") == 0;
#endif
  std::vector<Size> indices;
  if (parallel_registration)
  {
    std::set<std::string> native_ids;
    for (Size index = 0; index < map.size(); ++index)
    {
      const auto& spec = map[index];
      if (spec.getMSLevel() != ms_level) { continue; }
      const auto& id = spec.getNativeID();
      // Duplicate or previously registered keys retain the serial overwrite order.
      if (! native_ids.insert(id).second || native_id_precursor_peak_group_map_.contains(id))
      {
        parallel_registration = false;
        break;
      }
      indices.push_back(index);
    }
    if (indices.size() < 2) { parallel_registration = false; }
  }
  if (parallel_registration)
  {
    struct PrecursorJob
    {
      Size index;
      int before_scan;
      int after_scan;
      double start_mz;
      double end_mz;
    };
    std::vector<PrecursorJob> jobs;
    jobs.reserve(indices.size());
    std::exception_ptr preparation_error;
    // Keep scan-ID parsing and warnings on the caller, in input order.
    for (Size index : indices)
    {
      try
      {
        const auto [before_scan, after_scan] = findScanNumberBounds_(map, index, ms_level);
        const auto [start_mz, end_mz] = getIsolationWindowMzRange_(map[index]);
        jobs.push_back({index, before_scan, after_scan, start_mz, end_mz});
      }
      catch (...)
      {
        preparation_error = std::current_exception();
        break;
      }
    }
    // Read the same inclusive survey range in reverse order without copying spectra.
    const auto find_match = [&deconvolved_spectra, ms_level](const PrecursorJob& job) -> const PeakGroup* {
      const auto begin = std::lower_bound(deconvolved_spectra.begin(), deconvolved_spectra.end(), DeconvolvedSpectrum(job.before_scan));
      const auto after = std::lower_bound(deconvolved_spectra.begin(), deconvolved_spectra.end(), DeconvolvedSpectrum(job.after_scan));
      if (begin == deconvolved_spectra.end() || begin > after) { return nullptr; }
      auto survey = after == deconvolved_spectra.end() ? after : std::next(after);
      double max_score = -1.0;
      const PeakGroup* best = nullptr;
      while (survey != begin)
      {
        --survey;
        if (survey->getOriginalSpectrum().getMSLevel() != ms_level - 1 || survey->empty()) { continue; }
        for (const auto& pg : *survey)
        {
          if (pg[0].mz > job.end_mz || pg[pg.size() - 1].mz < job.start_mz) { continue; }
          double max_intensity = 0.0;
          const FLASHHelperClasses::LogMzPeak* selected = nullptr;
          const int charge = int(round(pg.getMonoMass() / job.start_mz));
          for (const auto& peak : pg)
          {
            if (peak.abs_charge != charge || peak.mz < job.start_mz || peak.mz > job.end_mz || peak.intensity < max_intensity) { continue; }
            max_intensity = peak.intensity;
            selected = &peak;
          }
          if (selected == nullptr) { continue; }
          const double score = pg.getChargeSNR(selected->abs_charge);
          if (score < max_score) { continue; }
          max_score = score;
          best = &pg;
        }
        if (best != nullptr) { break; }
      }
      return best;
    };
    std::vector<const PeakGroup*> matches(jobs.size(), nullptr);
    std::vector<std::exception_ptr> errors(jobs.size());
    if (! jobs.empty())
    {
      int team_size = 1;
#ifdef _OPENMP
      team_size = (int)std::min((Size)omp_get_max_threads(), jobs.size());
#endif
#pragma omp parallel for schedule(dynamic, 1) num_threads(team_size) default(none) shared(jobs, matches, errors, find_match)
      for (SignedSize job = 0; job < (SignedSize)jobs.size(); ++job)
      {
        try
        {
          matches[job] = find_match(jobs[job]);
        }
        catch (...)
        {
          errors[job] = std::current_exception();
        }
      }
    }
    // Publish the successful prefix before the earliest preparation/matching error.
    for (Size job = 0; job < jobs.size(); ++job)
    {
      if (errors[job]) { std::rethrow_exception(errors[job]); }
      if (matches[job] != nullptr) { native_id_precursor_peak_group_map_.emplace(map[jobs[job].index].getNativeID(), *matches[job]); }
    }
    if (preparation_error) { std::rethrow_exception(preparation_error); }
    return;
  }

  for (Size index = 0; index < map.size(); index++)
  {
    const auto& spec = map[index];
    if (spec.getMSLevel() != ms_level) { continue; }

    const std::string& native_id = spec.getNativeID();

    auto [b_scan_number, a_scan_number] = findScanNumberBounds_(map, index, ms_level);
    auto survey_scans = collectSurveyScans_(deconvolved_spectra, b_scan_number, a_scan_number, ms_level);
    if (survey_scans.empty()) { continue; }

    auto [start_mz, end_mz] = getIsolationWindowMzRange_(spec);
    PeakGroup best_pg = findBestPrecursorPeakGroup_(survey_scans, start_mz, end_mz);

    if (! best_pg.empty()) { native_id_precursor_peak_group_map_[native_id] = best_pg; }
  }
}

void FLASHDeconvAlgorithm::updatePrecursorQScores_(std::vector<DeconvolvedSpectrum>& deconvolved_spectra, int ms_level)
{
  // update precursor feature QScores and qvalues
  // Lower-level owners stay stable while only current-level precursor fields change.
  std::map<int, const DeconvolvedSpectrum*> scan_fullscan;

  for (auto& dspec : deconvolved_spectra)
  {
    if ((int)dspec.getOriginalSpectrum().getMSLevel() != ms_level - 1) continue;
    int scan = dspec.getScanNumber();
    scan_fullscan[scan] = &dspec;
  }

  for (auto& dspec : deconvolved_spectra)
  {
    if ((int)dspec.getOriginalSpectrum().getMSLevel() != ms_level) continue;
    if (dspec.getPrecursorPeakGroup().empty()) continue;

    auto precursor_pg = dspec.getPrecursorPeakGroup();

    int pscan = precursor_pg.getScanNumber();
    if (! scan_fullscan.contains(pscan)) continue;

    const auto& fullscan = *scan_fullscan[pscan];

    auto iter = std::lower_bound(fullscan.begin(), fullscan.end(), precursor_pg);

    if (iter == fullscan.end()) continue;

    if (precursor_pg.getMonoMass() == iter->getMonoMass())
    {
      precursor_pg.setFeatureIndex(iter->getFeatureIndex());
      precursor_pg.setQscore(iter->getQscore());
      if (iter->getFeatureIndex() > 0) precursor_pg.setQscore2D(iter->getQscore2D());
    }
    else
    {
      precursor_pg.setFeatureIndex(0);
    }
    dspec.setPrecursorPeakGroup(precursor_pg);
  }
}

void FLASHDeconvAlgorithm::runFeatureFinding_(std::vector<DeconvolvedSpectrum>& deconvolved_spectra,
                                              std::vector<FLASHHelperClasses::MassFeature>& deconvolved_features)
{
  if (merge_spec_ == 2) return;

  auto mass_tracer = MassFeatureTrace();
  auto decoy_mass_tracer = MassFeatureTrace();

  Param mf_param = param_.copy("ft:", true);

  if (((double)mf_param.getValue("mass_error_ppm")) < 0) { mf_param.setValue("mass_error_ppm", tols_[0]); }
  if (((double)mf_param.getValue("min_cos")) < 0) { mf_param.setValue("min_cos", min_cos_[0]); }

  mf_param.setValue("noise_threshold_int", .0);
  mf_param.setValue("reestimate_mt_sd", "false");
  mf_param.setValue("trace_termination_criterion", "outlier");
  mf_param.setValue("trace_termination_outliers", 20);
  mf_param.setValue("chrom_peak_snr", .0);

  mass_tracer.setParameters(mf_param); // maybe go to set param
  // Find features for MS1 or the minimum MS level in the dataset.
  deconvolved_features = mass_tracer.findFeaturesAndUpdateQscore2D(sd_.getAveragine(), deconvolved_spectra, (int)current_min_ms_level_, false);

  if (report_decoy_)
  {
    const auto& decoy_deconvolved_features
      = mass_tracer.findFeaturesAndUpdateQscore2D(sd_.getAveragine(), deconvolved_spectra, (int)current_min_ms_level_, true);
    deconvolved_features.insert(deconvolved_features.end(), decoy_deconvolved_features.begin(), decoy_deconvolved_features.end());
  }

  mf_param.setValue("min_trace_length", 1e-5); // allow all traces for MSn
  mass_tracer.setParameters(mf_param);
  // Find features for MSn
  for (int ms_level = (int)current_min_ms_level_ + 1; ms_level <= (int)current_max_ms_level_; ms_level++)
  {
    updatePrecursorQScores_(deconvolved_spectra, ms_level);
    std::map<uint, std::vector<Size>> feature_index_set;
    for (Size i = 0; i < deconvolved_spectra.size(); i++)
    {
      const auto& dspec = deconvolved_spectra[i];
      if ((int)dspec.getOriginalSpectrum().getMSLevel() != ms_level) continue;
      if (dspec.getPrecursorPeakGroup().empty()) continue;
      uint findex = dspec.getPrecursorPeakGroup().getFeatureIndex();
      if (findex == 0) continue;
      feature_index_set[findex].push_back(i);
    }

    for (const auto& element : feature_index_set)
    {
      std::vector<DeconvolvedSpectrum> tmp_dspec;
      tmp_dspec.reserve(element.second.size());
      for (Size i : element.second)
        tmp_dspec.push_back(deconvolved_spectra[i]);

      const auto& df = mass_tracer.findFeaturesAndUpdateQscore2D(sd_.getAveragine(), tmp_dspec, ms_level, false);
      deconvolved_features.insert(deconvolved_features.end(), df.begin(), df.end());

      if (report_decoy_)
      {
        const auto& df_decoy = mass_tracer.findFeaturesAndUpdateQscore2D(sd_.getAveragine(), tmp_dspec, ms_level, true);
        deconvolved_features.insert(deconvolved_features.end(), df_decoy.begin(), df_decoy.end());
      }

      Size j = 0;
      for (Size i : element.second)
        deconvolved_spectra[i] = tmp_dspec[j++];
    }
  }
}
} // namespace OpenMS